### ISSUE TITLE
We need Some More Function

### ISSUE THREAD

**Issue by webwayscript** [jrfeng/snow#6]
1. stop() or disconnect() not closing notification also even if we closed app (if we already stopped) notification not closed

2. Need One more icon inside notification called stop or close
    when click stop or close icon must service stopped and also must notification close

3. Need enable disable function for remove progress bar inside Notification. ( Live Stream no need this i think only play from local stored mp3  need this progress bar ??)

4. Now Song playing time if we receive call its muted that right working fine .. But we need enable disable function for on call finished start playing automatically .. if user enable it it resume automatically  or user need enable manually..

Thank you For you hard work ..

**Comment by jrfeng** [comment]
1. Invoke `PlayerCient#shudown()` can shutdown `PlayerService`. This will stop `PlayerService` and clear notification.
2. You need create a custom `NotificationView`. `NotificationView` alse have a `shutdown` method. You can customize all notification buttons: [`Create a notification with media controls`](https://developer.android.com/training/notify-user/expanded#media-style)
3. You need create a custom `NotificationView`, because this is android built-in style.
4. Can't do this, because when receive call, `PlayerService` will loss audio focus, then the player will pause. Can't on call finished start playing automatically. It's need yourself to handle this.

Note: After invoke `PlayerCient#shudown()`, all `PlayerClient` will disconnect automatically, because `PlayerService` is shutdown. You need reconnection your `PlayerClient`.

**Comment by webwayscript** [comment]
mPlayerClient.shutdown(); Working fine

But how can we use With dummy Seek bar inside notification??? You must fix it bro

**Comment by jrfeng** [comment]
What is "dummy seek bar"? can you please describe it in detail?

**Comment by webwayscript** [comment]
Its Use like fastForward()：and rewind()：Right? its only work non Online content like local stored mp3.. or may be Online mp3 ( Its must Buffering again when click ???? ) 
But its may be Dummy for Streaming link using shoutcast , icecast, all other streaming audio . So only we need enable disable function .. I know its complicated ..

**Comment by webwayscript** [comment]
Finally i fiund solutuion Just i passed duration "0" Not no seekbar in notification 
 MusicItem song1 = new MusicItemBuilder(0, "http://live.tamilkuyilradio.com:8026/rajaradio")
Thank you bro

**Comment by jrfeng** [comment]
`MusicItem` have a `setForbidSeek(boolean)` method, when play live stream, you can set this as `true`. This will forbid all seek action  `seekTo`, `fastForward` and `rewind`, example:

```java
MusicItem musicItem = new MusicItemBuilder(Integer.MAX_VALUE, "https://ww.example.com/example.m3u8")
                ....

                // Forbid Seek
                .setForbidSeek(true)

                .build();
```

**Comment by webwayscript** [comment]
Thank you its working fine
